[gsheets]
type = "service_account"
project_id = "kitchen-orders-467007"
private_key_id = "3ec245ada84bcf7d17e55607f1bc281933aec7d0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7HmK5Fj4zeNi3
OIsaXy9z6wZpn9TUuVMpc7ubrHyCjPl9I1iWqA0JnCOgun3dhyXOzTSha59AO3v+
IoNi7j+/tCvRkAht+Jwygjjxno1abb7us3TY5psCYHu5dUJacV0HVaS1WHgd1i6d
9EL4lZiZWbmoLZfj0YGOJ7QejjALZv7Q1G8YBTQRChKUZaGiCLNP0XJmjtmNHyjf
CxJr3CX0P73giijRTe12ZmUS1OOCcPelqDk12jryvvfHKGwwEk36xjx7XHapxP6L
SaC7ztmTo2ntcqYPZopWTDo+idooalmO4eGH+8pRuli7p15kPRBfC0tNkInzmgmz
XL/fNdORAgMBAAECggEACiT2kzQ6gQ3fKee92tsoNm+adGV+4118vbWRiToLsgQ0
jm05I0nPEyNM5yzVIApwqUqEvO+ZvaC78yYp21YxTJJXAdB+NIAS78YRkj/XR/zF
Kim+fvfZlYJnksFhrIeS1I/3EwHN2UhAVL3mV5W8pSuxHgYCww4bqPpMEJAC2MtP
7+U/l2mbx92wt/l8O28ooeSho6wRR+8EHfqQuE2Kxc+GFahcvA4JPQYpysEUAQab
N0kHY8P6VfSsS3r6IK0ys+l+pSH7wMNFQXWnuaARnZQxwHy7C1EjlU9xg6iWsvLS
Rgu1AxrKawUtiR2zPXmK3AWbqEziCa3ey3JD/dMdNQKBgQDcMTvNrXI05xGI1UiT
2GjTJ+G3SnrcVZnDMtJi8Jmm84q9y6yNWKv5mGRyBYImVWk40N8B36OWEN/4SRSk
WoxvFLA9pZIX7KG7DTiYStGJsyXihmTqgo5Hy4bW/P7RkOu5j94HmqXN9LqjdK6D
veOBznCP7nSso4vnaedW1HrjWwKBgQDZjEXhR1OTxcjxF8tnf3R+4eITIpV4NY3l
Rt4Q563GmMl4d4teMniAb5hoJGOd020IZ2TMpJRN2TlnqxcNGc33mscPAGZe1EPB
9nizwqOXFuc0fm+KaE0ilzvs8IyqPL5yZZ5BC/jbcwD3ChJDQaMZAfrxtIX48KpO
3TuFbH80gwKBgCJe9QzYBDnJz+ziDiA16bb8RLmNwLvgCM51gm27TODIp2GVB2xQ
6Rde+F7sCTLepjweLpFmTWzBWZSyI6y8DavROOmGjNV7NIu0Np9fHnI2KrW/cMVC
d98xH+0zNLuVuZYPpQLe2v7ZMsENF6is3XSHuv5cpI3GQbJvz5K4PC59AoGBALPi
oJnSL9K+NhTdVw0CwCJ2x0iJTUz0A5v1iIQz/mZ8SgO53d0LIMca/8wFYvXLMJpF
XH03DYZ9u1D0kP/9OWmnazgFXaDGJi0Jj+8cX8b8Yjvu3G53JmkW4q9ejQHrbpML
YdtpeeKD6uVbR5SjfqicEZOxcSJSZpEFsET4XQrfAoGBAIg/QOAFQeL9qudOosIY
PPKBZkPmartvlfR3jBEHXnuC+Cz/UpqWkYmJDbev0mdN1IBlT6IWVwvgQyZuFJFW
yBZA6BiUZNPAzdaLi/konoAEhHhRol9IitaUo3ypbh/PeHt9RGNctboqgp4xXs7o
FPmcQCYRrdC3z0iRaVIpRA1E
-----END PRIVATE KEY-----"""
client_email = "streamlit-kitchen-service@kitchen-orders-467007.iam.gserviceaccount.com"
client_id = "113634847564802572298"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-kitchen-service@kitchen-orders-467007.iam.gserviceaccount.com"
